### ISSUE TITLE
Issue on starter.js

### ISSUE THREAD

**Issue by krisanselmo** [CodinGame/SpringChallenge2021#1]
Hi, there is an issue in the js-starter Kit (https://raw.githubusercontent.com/CodinGame/SpringChallenge2021/main/starterAIs/starter.js):

`game.possibleAction.push(Action.parse(possibleAction))` should be replaced with `game.possibleActions.push(Action.parse(possibleAction))`

**Comment by adrienboulle** [comment]
and `game.possibleAction = []` should be `game.possibleActions = []`

**Comment by 2StepsFr0mHell** [comment]
Fixed, thanks!
